services:
  api:
    build:
      context: ../api
      dockerfile: ../api/Dockerfile
    ports:
      - "8080:8080"
  website:
    build:
      context: .
      dockerfile: Dockerfile.static-nginx
    ports:
      - "80:80"
