services:
  api:
    build:
      context: ../api
      dockerfile: ../api/Dockerfile
    ports:
      - "8080:8080"
  website:
    build:
      context: .
      dockerfile: Dockerfile.static-nginx
    environment:
      - VIDE_API_BASE=${VIDE_API_BASE:-}
      - VIDE_DOCUMENTS=${VIDE_DOCUMENTS:-}
    ports:
      - "80:80"
